spring.datasource.url=jdbc:postgresql://localhost:5433/careerhub
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# JWT Secret Key
app.jwt-secret=aaaabbbbccccddddeeeeffffgggghhhh
app.jwt-expiration-ms=86400000

# File Upload
app.upload-dir=/uploads

# Server Port
server.port=8080
